### ISSUE TITLE
ErrorCoded: Failed to load remote context 

### ISSUE THREAD

**Issue by oliviervd** [TREEcg/event-stream-client#19]
GET https://apidg.gent.be/opendata/adlib2eventstream/v1/industriemuseum/objecten
200 https://apidg.gent.be/opendata/adlib2eventstream/v1/industriemuseum/objecten?generatedAtTime=2021-07-31T18:23:55.534Z (938) ms
events.js:292
      throw er; // Unhandled 'error' event
      ^
ErrorCoded: Failed to load remote context https://apidg.gent.be/opendata/adlib2eventstream/v1/context/organisatie-basis.jsonld: Status code: 404
    at ContextParser.load (/usr/local/lib/node_modules/@treecg/actor-init-ldes-client/node_modules/jsonld-context-parser/lib/ContextParser.js:707:19)
    at async Promise.all (index 3)
    at async ContextParser.parse (/usr/local/lib/node_modules/@treecg/actor-init-ldes-client/node_modules/jsonld-context-parser/lib/ContextParser.js:597:30)
    at async EntryHandlerKeywordContext.handle (/usr/local/lib/node_modules/@treecg/actor-init-ldes-client/node_modules/jsonld-streaming-parser/lib/entryhandler/keyword/EntryHandlerKeywordContext.js:33:46)
    at async JsonLdParser.newOnValueJob (/usr/local/lib/node_modules/@treecg/actor-init-ldes-client/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:189:21)
    at async JsonLdParser.executeBufferedJobs (/usr/local/lib/node_modules/@treecg/actor-init-ldes-client/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:395:21)
Emitted 'error' event on JsonLdParser instance at:
    at JsonLdParser.onerror (internal/streams/readable.js:760:14)
    at JsonLdParser.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'loading remote context failed'
}

**Comment by pietercolpaert** [comment]
Can you confirm this issue has been solved? It works in each case on my machine
